### ISSUE TITLE
HRT Bus App: Press Release

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#13]
Write a press release to announce that hrtb.us is live in beta.

**Comment by kmcurry** [comment]
Example Press Releases:
https://docs.google.com/document/d/1sY5osRNgk_0kjnJUSQ0t8Eo_rKfTwuULgHejpYbjcbc/edit?usp=sharing
https://docs.google.com/document/d/1a1LX4vSggSeHQkzIKbUfPYh2hXvTX1OBXRWUDS5Nylc/edit?usp=sharing
https://docs.google.com/document/d/1kweKvqPx3lrbFztQvNFF4S59h6aaD2CFNsLzi-mxof8/edit?usp=sharing

**Comment by kmcurry** [comment]
Beth is working on this issue here:
https://docs.google.com/a/codeforamerica.org/document/d/1UfGOimFisLZsx10XlqRTNnFOqiP4shuiKUmz43l7deI/edit

**Comment by BethFisher** [comment]
Almost finished.  Need quotes.
