### ISSUE TITLE
Do something with restaurant, hotel and B&B inspection data

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#15]
http://www.healthspace.ca/Clients/VDH/VBeach/VBeach_Website.nsf

**Comment by kmcurry** [comment]
https://classic.scraperwiki.com/scrapers/vb_restaurant_inspections/

**Comment by kmcurry** [comment]
Probably belongs on the UserVoice as an idea

**Comment by BretFisher** [comment]
multiple repo's working on this idea.
