### ISSUE TITLE
Create indoc page for newbs

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#16]
Lets put ideas and resources here, and once we have enough for a page, we can create it as indoc.c4hrva.us or something.
## Purpose/goals
- three different audiences: 
  - people new on meetup.com
  - people new to physical hangout
  - people that stumble to codeforhamptonroads.org and want more info
  - cut down on the number of people thinking we'll teach them how to code. Give them the resources to learn on their own, and welcome them to the group if they still want to help. Be clear that we are not a education provider.
## What to call it? Some cool and meaningful name X.c4hrva.us
- indoc, newbs, intro, first, try, begin...
## How to build it (options)
- just static html page on github
- could use this bootstrap template to start http://twitter.github.io/bootstrap/examples/fluid.html
- use http://www.pathwright.com/ or similar service to create a free course
### Purpose and Foundation
- snip some text from our homepage, brigade site, and cfa
- background on cfa and brigade
- what is civic hacking
### Culture
- everything open: open source, open discussions
- we have many projects in many languages, but we're focused on the web (say what that does and doesn't mean)
### Communication
- core tools: google groups, meetup.com, irc, github, github, and oh, github
- get them to signup for each key tool: meetup, google groups, try IRC via webchat
### GitHub
- It's such a big part of everything we do, it deserves it's own section.
- Create their account (maybe do this last)
- View our projects, what do they mean, describe major sections of each project: repo, issues, wiki, etc.
- How to favorite, follow discussions, etc.
- http://try.github.io
- focus less on Git here, maybe put some about it in Coding below
### Coding
- choose your own adventure, focus on cross-platform web languages
- They can build something new, or help with any existing project
- We have plenty of things that need help
- Experienced: Some use the language they know, some want to learn a new lang
- point to online courses, free prefered, list others as well 
- http://www.codeschool.com
- http://www.codecademy.com
- http://www.codeyear.com
- HTML/CSS
- Python
- JavaScript/Nodejs
- Ruby
### Calls to Action
- What else can we inspire them to do?
- edit a github readme
- submit an app or data idea
- find some local open data we didn't know about
- help spread the word about the brigade to their communities

**Comment by jalbertbowden** [comment]
i've said it before but i'll say it again, i think adding a humans.txt file would be beneficial for n00bs. i think it would be beneficial for the landing page in general, but in this case getting people experience with github. all they'd have to do is access the the text file, add their information, submit pull request back. 

totally agree with pushing web platform.

**Comment by kmcurry** [comment]
Yeah, the coder-sounds repo at CfA was sort of like humans.txt. All fellows
had to do to earn their track jacket was add a line of text to the file, by
forking and submitting a pull request. +1 to the idea of a simple, discrete
task for "initiation" to the group that is really about teaching the skill.

On Saturday, July 20, 2013, albert wrote:

> i've said it before but i'll say it again, i think adding a humans.txt
> file would be beneficial for n00bs. i think it would be beneficial for the
> landing page in general, but in this case getting people experience with
> github. all they'd have to do is access the the text file, add their
> information, submit pull request back.
> 
> totally agree with pushing web platform.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/tasks/issues/16#issuecomment-21301279
> .

## 

Kevin Curry
Program Director
CfA Brigade
757.613.8158
GMT-4 (EDT)
http://brigade.codeforamerica.org

_Apply for Fellowship: http://codeforamerica.org/apply_

**Comment by bcbarsness** [comment]
I took a little different approach, more specific to a C4HRVA orientation with a procedural flavor, preferably limited to 1 or 2 pages. 

https://docs.google.com/file/d/0B9IPjM5DQQ1AXzJhWWd3Qm92Q0E/edit?usp=sharing

**Comment by jalbertbowden** [comment]
git for humans - add this vid to list http://www.youtube.com/watch?v=gp6v7AXQQTY&utm_content=buffer3e706&utm_source=buffer&utm_medium=twitter&utm_campaign=Buffer

**Comment by BretFisher** [comment]
**Big update:** content and your ideas have been moved into a new repo **welcome** that is a GitHub Pages site (using Jekyll) that's viewable here: http://welcome.codeforhamptonroads.org (shortcut: http://welcome.c4hrva.us). Read the [readme](https://github.com/c4hrva/welcome) for more info on how to use. I need to work on better navigation but the framing is there for us to crowdsource the content.

One thought of caution. CfA and Brigade sites have a lot of good content for intro to brigade, so we don't want to recreate or copy/paste that content. Link to it. The idea of this **welcome** site is that it's a prescribed walk-though of _all the things_ we end up pointing people to.  See [my goals](http://welcome.codeforhamptonroads.org/outline.html) at the top of the outline for my intent of this project. Feedback always welcome.

I say we now close this task and work on things in the **welcome** repo tasks and content.

**Comment by BretFisher** [comment]
[Welcome site](http://welcome.c4hrva.us) is nearly a year old, and continues to see content added. Mission accomplished.
