### ISSUE TITLE
Redirect hrtb.us to new UI and link new UI to map UI

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#18]
hrtb.us & go.hrtb.us/busfinder should bring up the interface at http://c4hrva.github.io/hrt-bus-finder/ and the interface at http://c4hrva.github.io/hrt-bus-finder/ should like to the map UI. Not sure if this should be an issue reported in the app repo(s).

**Comment by bschoenfeld** [comment]
The mapping is an open issue in that project - c4hrva/hrt-bus-finder#7

And I'm gunning for it :wink:

**Comment by kmcurry** [comment]
This is ready to close, yes?

**Comment by bschoenfeld** [comment]
Yep!
