### ISSUE TITLE
Do PR to local media

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#19]
- [x] Hearsay with Cathy Lewis
- [x] Hampton Roads Today on NBC
- [x] Daily Press
- [x] Virginian-Pilot
- [x] NSU
- [x] ODU
- [x] TCC
- [x] Thomas Nelson
- [x] Navy

**Comment by BethFisher** [comment]
Email content for blast email to riders from school campuses??

**Comment by BethFisher** [comment]
When media launches, we can do a CfA tumblr post

**Comment by kmcurry** [comment]
Most of these places were contacted and many more. See our spreadsheet. Would be good to follow up with another push.
