### ISSUE TITLE
Write E-mail templates for soliciting local colleges, et al

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#20]

**Comment by jalbertbowden** [comment]
templates: do you mean an html email, as well as the email content? if so, maybe we should start a mailchimp account for the brigade. pretty sure we get x number of emails for free to start, plus i want to say one of the features in localwiki was to start a newsletter, which we could easily incorporate into mailchimp as well. just a thought.

**Comment by kmcurry** [comment]
Content.

**Comment by kmcurry** [comment]
https://docs.google.com/a/codeforamerica.org/document/d/1adp-SBN4lmYe84owJ85VerCOfD_niZHusouaE8cvPMA/edit#
