### ISSUE TITLE
Draft Requirement for ePro API Interfaces

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#21]
City of Virginia Beach CommIT would like an articulated requirement for what we want from ePro and how we want to get it from an API.

Ex., return JSON from methods such as:

/incident/12345
/incidents/010113-121213
##

**Comment by BretFisher** [comment]
working the requirements here: https://docs.google.com/document/d/1T8tdOY_4yBSP7orbXMlvEhUjqezqcUz7A72ZrxEWdck/edit?usp=sharing

**Comment by qwo** [comment]
@kmcurry I'm going to close this.
