### ISSUE TITLE
Provide CVB feedback on vbgov.com data that needs "opening"

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#22]
Hunt down .pdf, .csv, .html, etc. data that we think would be useful in open machine-readable formats (csv, json, xml, api) and send that data back to Bret's contact in ComIT (Kevin Fairley).

Here's a running list for all to add to (or add to this issue): http://goo.gl/1UKHUh
##

**Comment by qwo** [comment]
@BretFisher @kmcurry closing this we have a data portal now.
