### ISSUE TITLE
Write City Job descriptions for C4HRVA volunteers

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#23]
developers, designers, data hackers, etc.

City of Virginia Beach gets thousands of volunteers each year, and the way they look for work is through job postings inside the city for volunteer needs.  We should write up what skills we need and give to City's Volunteer Office.
##

**Comment by BethFisher** [comment]
How 'bout something like this?

CIVIC-MINDED TECHNOLOGISTS
Lend your skills in writing code, developing websites, designing websites, writing copy, creating graphics to help the City leverage its data to create apps and improve communications.
Code for Hampton Roads is a volunteer chapter of Code for America Brigade. Code for America Brigade is an organizing force for local civic engagement ­ a national network of civic-­minded volunteers who contribute their skills toward using the web as a platform for local government and community service. COMMITMENT — 3 hours each Wednesday, 6-9 p.m.

I used this web page for guidance... http://www.vbgov.com/government/departments/courts/court-services-unit/pages/volunteer-opportunities.aspx

**Comment by qwo** [comment]
closing
