### ISSUE TITLE
Norfolk flood zone mapping mobile app

### ISSUE THREAD

**Issue by BethFisher** [Code4HR/tasks#24]
create a mobile web app for plugging in your address to find out if your property is in a flood zone and if so, which zone.
##

**Comment by vaslims** [comment]
Test

**Comment by kmcurry** [comment]
How deep is the water where I'm standing if...?

**Comment by kmcurry** [comment]
This feels like it should be an idea on our UserVoice instead of a task: http://c4hrva.uservoice.com/forums/103669-code-for-hampton-roads I see Open Budget as a task, too. Thinking on it more...
