### ISSUE TITLE
Code Across Communications

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#27]
- [x] Draft save the date
- [x] Eventbrite [CodeAcrossHR](codeacrosshr.eventbrite.com), shorturl is http://bit.ly/cahr2014
- [x] Media and Design - codeacross 2014 and localized event media
- [x] CodeforhamptonRoads Page temp: http://code-across-2014-c4hr.azurewebsites.net (page auto-deploys the [code-across-2014 branch](https://github.com/c4hrva/c4hrva-landing/tree/code-across-2014) of the landing repo)

**Comment by kmcurry** [comment]
@BretFisher I see that the branch is for a Code Across update to the homepage. For codeacross.codeforhamptonroads.org do we create a new repo and gh-pages just like welcome?

**Comment by qwo** [comment]
I'm unfamiliar with hover and how the current subdomain scheme works for http://welcome.codeforhamptonroads.org

I'm attempting to mimic it currently.

I created a codeacross repo and linked the cname @ https://github.com/c4hrva/codeacross and linked it to  http://codeacross.codeforhamptonroads.org

Not trying to reinvent the wheel but I'd be up for creating a stand-alone hack-a-thon landing page. Possibly It could be templatized and localized for other brigades and orgs participating.

I think having a standalone website/subdomain that looks distinct adds to an event and gives it more importance. 

Some inspiration hack event pages  i've seen

http://hackvirginia.org/ (i co-created) 
http://hackforwesternmass.org/ (the national day of civic hacking templates) 
http://www.hackmit.org/
http://www.mhacks.org/
http://angelhack.com/

I can work on a page if i get a go ahead?

**Comment by jalbertbowden** [comment]
grab berlin.js theme. i have starred a few nice themes for small sites, but
that one ive been staring @ in particular for a long time

On Friday, December 13, 2013, Stanley Zheng wrote:

> I'm unfamiliar with hover and how the current subdomain scheme works for
> http://welcome.codeforhamptonroads.org
> 
> I'm attempting to mimic it currently.
> 
> I created a codeacross repo and linked the cname @
> https://github.com/c4hrva/codeacross
> 
> Not trying to reinvent the wheel but I'd be up for creating a stand-alone
> hack-a-thon landing page. Possibly It could be templatized and localized
> for other brigades and orgs participating.
> 
> I think having a standalone website/subdomain that looks distinct adds to
> an event and gives it more importance.
> 
> Some inspiration hack event pages i've seen
> 
> http://hackvirginia.org/ (i participating)
> http://hackforwesternmass.org/ (the national day of civic hacking
> templates)
> http://www.hackmit.org/
> http://www.mhacks.org/
> http://angelhack.com/
> 
> I can work on a page if i get a go ahead?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/tasks/issues/27#issuecomment-30525107
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by BretFisher** [comment]
We have multiple needs here.  Give me a few hours to finish work and I'll
break this out with tasks/details in this task and on emails.  Thanks for
helping yo!

**Comment by BretFisher** [comment]
@stanzheng  to point subdomain to a github repo, you have to:
1. create `gh-pages` branch in repo and use that to update content (basically ignoring or deleting master branch)
2. create `CNAME` file to tell github to accept the DNS you changed and send it to `gh-pages` branch
3. update hover.com DNS (something I normally do) to point the A record codeacross to github pages IP address

by the looks of it all you need is the last step.

However, do we really need a separate site/repo? Seems more complex than needed. We've already got the `code-across-2014` branch which is a beta of existing codeforhamptonroads.org, which auto deploys here for testing: http://code-across-2014-c4hr.azurewebsites.net

To me we have two goals with the updated site:
- educate attendees about the event: this is what I'm hoping we will add to the front page in `code-across-2014` branch. It's what people see when they go to our home page, rather than some "click here" to take them elsewhere.
- call to action for donors (sponsors)

For the first bullet, all we need is some attention on the current `\index.html`. A paragraph about event, list of current donors, and info will grow as we get closer.

For the 2nd bullet, I think we need an additional single page. I'd added a template from Start Bootstrap to a sub folder `support` on that branch. So it would be codeforhamptonroads.org/support

All I've changed is the title, obviously it needs create-commons photos (flickr) and proper content.

It could also be renamed to something else, or have DNS redirects from anything.codeforhamptonroads.org etc.

If this is cool, it gives us enough to start with so that all can chip in w/o me being the hold up :)

**Comment by qwo** [comment]
I'd be up for using the existing c4hrva landing branch. would it cause
complexity on the end of creating it as a fork on the landing page for
other brigades who have forked the page.

it seems very much like semantics since a branch can become its own repo
later on.

In all I get your point, using the current style than a complete overhaul.

If you can point http://codeacross.codeforhamptonroads.org  on hover to the
branch on the landing page we can work from there.

On Sun, Dec 15, 2013 at 1:32 PM, Bret Fisher notifications@github.comwrote:

> @stanzheng https://github.com/stanzheng to point subdomain to a github
> repo, you have to:
> 1. create gh-pages branch in repo and use that to update content
>    (basically ignoring or deleting master branch)
> 2. create CNAME file to tell github to accept the DNS you changed and
>    send it to gh-pages branch
> 3. update hover.com DNS (something I normally do) to point the A
>    record codeacross to github pages IP address
> 
> by the looks of it all you need is the last step.
> 
> However, do we really need a separate site/repo? Seems more complex than
> needed. We've already got the code-across-2014 branch which is a beta of
> existing codeforhamptonroads.org, which auto deploys here for testing:
> http://code-across-2014-c4hr.azurewebsites.net
> 
> To me we have two goals with the updated site:
> - educate attendees about the event: this is what I'm hoping we will
>   add to the front page in code-across-2014 branch. It's what people see
>   when they go to our home page, rather than some "click here" to take them
>   elsewhere.
> - call to action for donors (sponsors)
> 
> For the first bullet, all we need is some attention on the current
> \index.html. A paragraph about event, list of current donors, and info
> will grow as we get closer.
> 
> For the 2nd bullet, I think we need an additional single page. I'd added a
> template from Start Bootstrap to a sub folder support on that branch. So
> it would be codeforhamptonroads.org/support
> 
> All I've changed is the title, obviously it needs create-commons photos
> (flickr) and proper content.
> 
> It could also be renamed to something else, or have DNS redirects from
> anything.codeforhamptonroads.org etc.
> 
> If this is cool, it gives us enough to start with so that all can chip in
> w/o me being the hold up :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/tasks/issues/27#issuecomment-30615630
> .

## 

Stanley Zheng
B.S. Comp Sci ODU '14
Cell: (347)-399-3732
@stanzheng

**Comment by BretFisher** [comment]
I wouldn't worry about forking. Hasn't stopped others in past. I also don't
require any of you to fork this code just edit things on the code across 14
branch

With my recommended changes there are no DNS entries needed. Let me
clarify, the code across 14 branch is a testing and development branch
only, and will be merged into the gh-pages branch once were ready to go
live with our changes. The Azure website that I mentioned is only used for
us in testing purposes.

**Comment by qwo** [comment]
ok cool. makes sense.

 the only issue i had was i've had experience primarily with Bootstrap 3.

I will try to work it out. Thanks Bret

On Sun, Dec 15, 2013 at 2:13 PM, Bret Fisher notifications@github.comwrote:

> I wouldn't worry about forking. Hasn't stopped others in past. I also
> don't
> require any of you to fork this code just edit things on the code across
> 14
> branch
> 
> With my recommended changes there are no DNS entries needed. Let me
> clarify, the code across 14 branch is a testing and development branch
> only, and will be merged into the gh-pages branch once were ready to go
> live with our changes. The Azure website that I mentioned is only used for
> us in testing purposes.
> 
> On Sunday, December 15, 2013, Stanley Zheng wrote:
> 
> > I'd be up for using the existing c4hrva landing branch. would it cause
> > complexity on the end of creating it as a fork on the landing page for
> > other brigades who have forked the page.
> > 
> > it seems very much like semantics since a branch can become its own repo
> > later on.
> > 
> > In all I get your point, using the current style than a complete
> > overhaul.
> > 
> > If you can point http://codeacross.codeforhamptonroads.org on hover to
> > the
> > branch on the landing page we can work from there.
> > 
> > On Sun, Dec 15, 2013 at 1:32 PM, Bret Fisher <notifications@github.com<javascript:_e({},
> > 'cvml', 'notifications@github.com');>>wrote:
> > 
> > > @stanzheng https://github.com/stanzheng to point subdomain to a
> > > github
> > > repo, you have to:
> > > 1. create gh-pages branch in repo and use that to update content
> > >    (basically ignoring or deleting master branch)
> > > 2. create CNAME file to tell github to accept the DNS you changed and
> > >    send it to gh-pages branch
> > > 3. update hover.com DNS (something I normally do) to point the A
> > >    record codeacross to github pages IP address
> > > 
> > > by the looks of it all you need is the last step.
> > > 
> > > However, do we really need a separate site/repo? Seems more complex
> > > than
> > > needed. We've already got the code-across-2014 branch which is a beta
> > > of
> > > existing codeforhamptonroads.org, which auto deploys here for
> > > testing:
> > > http://code-across-2014-c4hr.azurewebsites.net
> > > 
> > > To me we have two goals with the updated site:
> > > - educate attendees about the event: this is what I'm hoping we will
> > >   add to the front page in code-across-2014 branch. It's what people see
> > >   when they go to our home page, rather than some "click here" to take
> > >   them
> > >   elsewhere.
> > > - call to action for donors (sponsors)
> > > 
> > > For the first bullet, all we need is some attention on the current
> > > \index.html. A paragraph about event, list of current donors, and info
> > > will grow as we get closer.
> > > 
> > > For the 2nd bullet, I think we need an additional single page. I'd
> > > added
> > > a
> > > template from Start Bootstrap to a sub folder support on that branch.
> > > So
> > > it would be codeforhamptonroads.org/support
> > > 
> > > All I've changed is the title, obviously it needs create-commons
> > > photos
> > > (flickr) and proper content.
> > > 
> > > It could also be renamed to something else, or have DNS redirects from
> > > anything.codeforhamptonroads.org etc.
> > > 
> > > If this is cool, it gives us enough to start with so that all can chip
> > > in
> > > w/o me being the hold up :)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/c4hrva/tasks/issues/27#issuecomment-30615630>
> > > .
> > 
> > ## 
> > 
> > Stanley Zheng
> > B.S. Comp Sci ODU '14
> > Cell: (347)-399-3732
> > @stanzheng
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/c4hrva/tasks/issues/27#issuecomment-30616298>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/tasks/issues/27#issuecomment-30617707
> .

## 

Stanley Zheng
B.S. Comp Sci ODU '14
Cell: (347)-399-3732
@stanzheng

**Comment by BretFisher** [comment]
done :)
