### ISSUE TITLE
Code Across Fundraising

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#29]
- [x] Send out save the date to potential funders
- [x] Create landing page for "selling" the event to potential donors (http://startbootstrap.com/stylish-portfolio) and link/embed donation page (https://secure.codeforamerica.org/page/contribute/2013-annual-campaign)
- [x] List of prizes we want them to fund/provide
- [x] Branch landing page with CA and donors highlighted https://github.com/c4hrva/c4hrva-landing/tree/code-across-2014
- [x] Food vendors - breakfast, lunch, snack for Saturday

**Comment by BretFisher** [comment]
**Costs to Cover**
Heavy Hors D'oeuvres Friday Night
Beverages Friday Night
Breakfast Saturday
Lunch Saturday
Dinner Saturday
Displays/Signs/Printing

**Door Prizes**
[Raspberry Pi Starter Kit](http://www.makershed.com/Raspberry_Pi_Starter_Kit_p/msrpik.htm)

**Medium Prizes**
Nexus Tablets (for testing!)
Adobe Creative Suite

**Big Prizes**
[Yoga 2 Pro $999](http://www.bestbuy.com/site/ideapad-yoga-pro-2-ultrabook-2-in-1-13-3-touch-screen-laptop-4gb-memory/1838553.p?id=1219065987641&skuId=1838553&st=yoga%202%20pro&cp=1&lp=2)
[Macbook Air 13" $1099](http://store.apple.com/us/buy-mac/macbook-air?product=MD760LL/A&step=config)

**Comment by kmcurry** [comment]
I'm editing the list in @BretFisher's comment so it doesn't get split up.

**Comment by bschoenfeld** [comment]
I thought we had a spreadsheet for this

https://docs.google.com/spreadsheet/ccc?key=0ApfMNDGiGLqodHlIalpoc1c0LU1ROW80VGFhOWxvRVE&usp=docslist_api

**Comment by kmcurry** [comment]
Sorry, boss. Was just following your lead here. Right you are.

On Thu, Jan 9, 2014 at 7:59 AM, Ben Schoenfeld notifications@github.comwrote:

> I thought we had a spreadsheet for this
> 
> https://docs.google.com/spreadsheet/ccc?key=0ApfMNDGiGLqodHlIalpoc1c0LU1ROW80VGFhOWxvRVE&usp=docslist_api
> 
> On Wednesday, January 8, 2014, Kevin Curry wrote:
> 
> > I'm editing the list in @BretFisher https://github.com/BretFisher's
> > comment so it doesn't get split up.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/c4hrva/tasks/issues/29#issuecomment-31898571>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/tasks/issues/29#issuecomment-31928331
> .

## 

Kevin Curry
Advisor, Civic Hacker
Code for America
http://brigade.codeforamerica.org

Let's CodeAcross together this February 21-23:
http://www.codeforamerica.org/codeacross

**Comment by BretFisher** [comment]
done
