### ISSUE TITLE
App Idea: Find Your First Responders

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#30]
need:
how do you know where your likely first responders come from?
how could you thank them?
how do you know which rescue squad is yours, esp for donating to?

potential solution:
maybe rescue squad focused, maybe all first responders...

web app, using location data or manual address, shows you the most likely responders, particularly fire/rescue. options from there are:
thank them (sends a snazzy pre-form email)
contact info
call to action to join
call to action to donate to them
assuming the rescue squads like it, they could list it on their sites to get word out. There are 10 squads in VB, all of which are their own entity and do their own fund raising. I don't know how to tell which ones would cover my home, so not sure which one to donate to... so then this idea came up.

data needed:
geodata response grids for each resque squad, assuming they work that way and would give up the data.

stretch goal: national coverage of single site, run off github repo that takes geodata pull requests from others.

I know very little about this, just had a idea and was looking for info/feedback. Some background info from one of the local squads: http://www.vbrescuefoundation.org
##

**Comment by BretFisher** [comment]
Kevin's response: The folks at Recovers.org and #crisiscommons might know more. Any potential, local champions in the the emergency response community that you know?

Melissa's response: Let me know if you need contacts for this. Also, Public Safety has their own GIS guy, He’s awesome.

**Comment by bschoenfeld** [comment]
A good starting point for this app may be [Code for Boston's Pantry Pickup App](http://www.pantrypickup.org/). Their app helps people find and donate food to near-by food pantries. I was thinking of spinning that app off to do animal shelters, but this idea could work too. Possible that this could end up looking like CfA's adopt-a effort. There could be a series of donate-to apps.

**Comment by qwo** [comment]
closing.
