### ISSUE TITLE
Idea: Tunnel Closing Graphic

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/tasks#33]
I hope everyone knows about [Nikki Sylianteng's Parking Sign Redesign](http://nikkisylianteng.com/project/parking-sign-redesign/). It's great.

I just saw the latest press release from ERT about the tunnel closing schedule and it's awful. Maybe we can do something like the parking sign redesign. Any designers want to take a shot at it?

![screen shot 2014-07-16 at 5 23 03 pm](https://cloud.githubusercontent.com/assets/565347/3605841/7c707a9e-0d2f-11e4-83fe-9ab21c80a9ac.png)
![screen shot 2014-07-16 at 5 23 20 pm](https://cloud.githubusercontent.com/assets/565347/3605842/7f5a9d98-0d2f-11e4-9733-ff0ac6b28042.png)
##

**Comment by qwo** [comment]
first time hearing about it 

@aureately take a look at this! Do you know any friends that would be interested in this?

**Comment by qwo** [comment]
i think also @aimsrandom took a look at this at hacknight.

Since the time schedule is short and its starting in 5 days? why dont we make a website.

Isthetunnelclosed.com
- [ ] YES
- [ ] NO
- [ ] YES ... - Will be closed within the hour.

i think you pitched this before @bschoenfeld

**Comment by bschoenfeld** [comment]
That's not a bad idea. I was also thinking of making a graphic that could
be released to the press as a substitute for what they sent out. Maybe a
calendar makes the most sense. But I was thinking maybe a graphic
representing the tunnels and all 4 lanes (maybe from above) with the sides
labeled Portsmouth and Norfolk and then overlay the weeks and weekends or
whatever makes sense and use red and green to represent which lanes are
closed and which are opened.

We should have played with the one the whiteboard last night.

**Comment by jalbertbowden** [comment]
http://thenounproject.com/term/bridge-damaged/4362/
http://thenounproject.com/term/bridge-destroyed/4363/
random implementation..i reckon for desktop: http://adib.typepad.com/blog/images/2008/03/25/icon_closec.jpg

**Comment by qwo** [comment]
closing
