### ISSUE TITLE
New Gravatar Icon for Organization

### ISSUE THREAD

**Issue by qwo** [Code4HR/tasks#34]
Hi,

I'm not sure if this is a long standing github outage issue but the gravatar is still down. reuploading it could be ideal or what?

best,

**Comment by BretFisher** [comment]
what do you mean? 
![code_for_hampton_roads__norfolk_virginia_beach_](https://cloud.githubusercontent.com/assets/792287/3621842/9ff66c20-0e20-11e4-8b8a-dee0fa93d9fb.png)

**Comment by qwo** [comment]
I guess it must just be, closing 
![screenshot 2014-07-17 22 33 06](https://cloud.githubusercontent.com/assets/3683993/3621981/2296debe-0e24-11e4-97bc-3b48333b4945.png)
