### ISSUE TITLE
Idea: Swapping out the landing site. 

### ISSUE THREAD

**Issue by qwo** [Code4HR/tasks#37]
the two features i like are the projects list and the issue list.

@BretFisher how are your feelings with making it live?

there are some of the tasks that need to be done before htis is live
- [x] swap image
- [x] news letter button
- [ ] more sollicite feedback 
- [ ] github projects page url

http://c4hrva.github.io

**Comment by BretFisher** [comment]
I like it, short and sweet. I wish we we're tracking engagement in Google
Analytics for clicking meetup or newsletter so we could compare after
switching to this, but that's not a reason to delay. Let me take a deeper
look at it. I'm seeing some things we may need to add/remove. GOOD WORK +1

**Comment by BretFisher** [comment]
So the CFAPI dumps our project list from github right now. It could use a
google sheet like they link to on the project page of this repo, but it's
not using that yet.

Looks like you created this sheet
https://docs.google.com/spreadsheet/ccc?key=0AnyyYdD_lUkrdHlNRm9XS1NZRGtfTUFDLWJkUllhcGc&usp=sharing?
and once we update it using this CFAPI standard
https://github.com/codeforamerica/cfapi#projects-list we can update the
CFAPI sheet
https://docs.google.com/spreadsheet/ccc?key=0ArHmv-6U1drqdGNCLWV5Q0d5YmllUzE5WGlUY3hhT2c&usp=sharing
with our sheet rather then github url?

**Comment by qwo** [comment]
yes @BretFisher exactly, that is the todo i forgot to add, the curated list was something i was trying to work on last hack night.

The projects cfapi dump takes a while if its a bunch of files like they had.
