### ISSUE TITLE
Link old domain 

### ISSUE THREAD

**Issue by qwo** [Code4HR/tasks#40]
Old website http://codeforhamptonroads.org/ should point to -> code4hr.org

 also old codeforvb.org

**Comment by BretFisher** [comment]
Yea, they do. hover is not working. gonna have to get their support involved.

**Comment by BretFisher** [comment]
partially fixed. working on www.

**Comment by BretFisher** [comment]
only thing not working is www.code4hr.org and have a support ticket into hover.com for that.

**Comment by BretFisher** [comment]
OK learning that hover.com kinda sucks for cloud computing where you need CNAMES on apex domains. In the future I will be moving everything to dnsimple.com

**Comment by qwo** [comment]
+1 for dnsimple!
