### ISSUE TITLE
Homelessness Resources

### ISSUE THREAD

**Issue by wbprice** [Code4HR/tasks#43]
Would be interesting to build something akin to http://sheltr.org/ for Hampton Roads. 
- Audience would be people experiencing homelessness or people who want to help, but don't know where shelters/foodbanks are.
- MVP would be an SMS endpoint taking a location code (provided by sticker?) and returning nearest shelter/food locations.
## Partners
- Cities
  - City of Norfolk is interested in helping with homelessness challenges.
  - VA Beach, etc?
    - [Lighthouse Center](http://www.voachesapeake.org/lighthouse-center) Deborah Maloney
- Shelters and Food Banks (providers)
## Challenges: 
- How do people get this information now?  How would this improve on the existing process?
- % of audience that has feature phones and could use this service?
- How frequently do provider locations/hours change?
##

**Comment by kmcurry** [comment]
[#withnotfor](https://twitter.com/hashtag/withnotfor) reminder to ensure that members of the audience as well as human and social services communities are in the conversation from the beginning.

**Comment by wbprice** [comment]
Editing the above comment to that effect +1

**Comment by kmcurry** [comment]
Food Bank of Southeastern Virginia

**Comment by kmcurry** [comment]
Search open211

**Comment by ghost** [comment]
Using [today's meetup](http://www.meetup.com/Code4HR/events/213694792/) to help provide some resources on OpenStreetMap.  @jonahadkins will help put in some resources as well.
- [Foodbank of Southeastern Virginia and the Eastern Shore](https://www.openstreetmap.org/way/312967332)
- [Lighthouse Centre](https://www.openstreetmap.org/way/312974084)

**Comment by jonahadkins** [comment]
Adding Shelters For Norfolk [From This List](http://www.homelessshelterdirectory.org/cgi-bin/id/city.cgi?city=Norfolk&state=VA) And [These Too!](http://norfolk_va.suntopia.org/homeless_shelters.php)

**Comment by DaveHarrisVA** [comment]
All services on this sheet should have information verified and be added.  <a href="http://www.norfolkhomelessconsortium.org/cmc/street-sheet-march-2011.doc">Norfolk Street Sheet</a>

It MAY be feasible to include the NEST schedule into our data and display it based on the current date.  NEST is a winter sheltering program where participants rotate between churches each week sheltering the homeless.  There are usually two churches at a time participating, one is a walk-up church accessible from downtown and one buses participants to it from Monticello Ave.  Virginia Beach and Chesapeake also have similar programs I think.

**Comment by qwo** [comment]
Awesome Thanks for sharing this @DaveHarrisVA had no idea this existed. How do people use this data? who usually checks this out and this is pretty static right since the date on it is 2011

**Comment by DaveHarrisVA** [comment]
Yes, it's typically given to homeless people to help them find services.  A dynamically generated "printout" based on current data sources (that can be made public) would be very helpful!

**Comment by qwo** [comment]
are these typically given out by the churchs themselves. making data available in a way everyone can find would be awesome

**Comment by qwo** [comment]
are these typically given out by the churchs themselves. making data available in a way everyone can find would be awesome

**Comment by DaveHarrisVA** [comment]
Yes, by churches, service providers, soup kitchens, Union Mission, city offices, community services board, etc.  It may be possible to set up an appointment with the Norfolk Office to end Homelessness to discuss this project further and what would be most beneficial to service providers and homeless individuals since I don't think we should do it without input as to what they need

**Comment by DaveHarrisVA** [comment]
@wbprice email me if you want to set up a meeting with the Norfolk Office to end Homelessness to discuss this since I have to leave the library today at 4PM or a meeting to discuss this idea before then

**Comment by wbprice** [comment]
@DaveHarrisVA I don't have your email address, but you can email me at bprice@codeforamerica.org.  If you're not already in there, I can always be reached by Slack as well. https://codeforva.slack.com/

**Comment by DaveHarrisVA** [comment]
Check your email from Stanley Z yesterday

**Comment by qwo** [comment]
closing
