### ISSUE TITLE
CodeAcross 2015 Planning

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#44]
Add to the task list, discuss, help by working on a task and reporting back here. [Some other notes we have in Google Docs are here](https://drive.google.com/open?id=1bffDCS7T9Ey063vPkg-lyVruVBdmMwsf4VKleD5FCo4&authuser=0).
- [x] Determine format/schedule given theme ([Principles for 21st Century Government](http://www.codeforamerica.org/governments/principles/))
  - [Schedule](https://docs.google.com/document/d/1Vp-lwKizYS9zYi_JlQLxyTPiT1psNd3jU0OVhelL6CU/edit?usp=sharing)
- [x] Fill out CfA event signup @BretFisher
- [x] Pick chair-persons for code4hr (we're just gonna wing it)
- [x] Create eventbrite event @stanzheng http://code4hr.eventbrite.com
- [x] Create meetup.com event (used as a pointer to eventbrite)
- [x] [Update contacts](https://drive.google.com/open?id=0AvWC8QOgiwjzdGluMTdwMzVjbXpWbFBSWDJhcmdGY3c&authuser=0) list for media, corporate, gov
- [x] Lock in venue
- [x] List things we need money for
  - [sheet of catering options from last year, add more plz](https://docs.google.com/spreadsheet/ccc?key=0AmxrhNF-KxSpdEhLeVRscm1lZnRUYVA2b09nQk9JREE&usp=sharing)
  - [x] Breakfast
  - [x] Lunch
  - [ ] Espresso cart?
  - [ ] Happy hour after event
  - [ ] Giveaways (not prizes)
    - [ ] Tshirt this year?
    - [ ] Legal-ish size posters? (would need good custom graphics)
  - [ ] Contests and Prizes?
- [x] Lock in major local ~~sponsors~~ donors ([last years donation spreadsheet](https://docs.google.com/spreadsheets/d/1kfznA8rK36CGRRqhwdz5DnjqvM-FuBoB-YZzYNEcj1Y/edit?usp=sharing))
  - [ ] Wait till we know what we need (Donation Prospectus) before asking for money 
  - [ ] ashleighs@inmotionhosting.com - Ashleigh Smith
  - [ ] missy@xtuple.com - Missy Schmidt
  - [ ] mpaddock@thisisgrow.com - Matt Paddock
  - [ ] aaron.snead@udig.com - Aaron Snead
  - [x] CodeBetter.org $500
  - more on last years spreadsheet
- [x] signage
  - [x] at least several large signs to welcome them, point them where to go
  - [x] need graphics to take for printing
- [x] Create event page on code4hr.org
  - [x] CA [Logos](https://drive.google.com/folderview?id=0B8wnT8pwztFCTXg5c2p2N0lsR2M&usp=sharing)
- [ ] Create open data list for event (work off DE October event?)
  - [x] [Open Data Census](http://us-city.census.okfn.org/), ex., [Va Beach](http://us-city.census.okfn.org/place/vabeach)
- [ ] Create existing project list for "work on existing" (work off DE winners + code4hr major projects)
- [x] Make a list of workshops and find people to run them.
  - [x] Github - Linda Nichols
  - [x] OpenStreetMap Workshop - Jonah Adkins 
  - [ ] Wordpress?
  - [ ] Node.js or Meteor? - more technical yes, but could be a draw to more dev's
  - [ ] Roundtable presentation on public data vs. open data, do's and don'ts of open data?

**Comment by kmcurry** [comment]
BIG :+1:

**Comment by kmcurry** [comment]
http://www.meetup.com/Code4HR/events/218893449/

**Comment by kmcurry** [comment]
Slover Library! Should be open and ready for us by then, right?

**Comment by BretFisher** [comment]
Thoughts on giveaways? Maybe have a sponsored t-shirt with a great custom design? Also need more workshop and roundtable ideas. Also could use some 2015-style prize ideas.

**Comment by qwo** [comment]
i put a flat number of $500 for the budget allocation. would these all be sponsored prizes?

**Comment by jonahadkins** [comment]
Ill Run An OpenStreetMap Workshop -- Will Also Do Something With Open Data Or GIS 4 noobs or Whatever :+1: :earth_africa:

**Comment by qwo** [comment]
@lynnaloo talked with @wbprice about a github workshop

edit: sent @github a request for swag.

**Comment by qwo** [comment]
since <1 month, recommended the codeacross cfa page is our main event landing and the eventbrite at 

http://code4hr.eventbrite.com will be the event signup.
http://www.codeforamerica.org/events/codeacross-2015/

**Comment by kmcurry** [comment]
Which spaces are we in?

**Comment by qwo** [comment]
i currently only reserved the one across from the state room on the 6th floor. see email for pictures.

spreading outspace will likely be one level down in the break off rooms. they are open to us having to reserve more spaces.. but none of them are in a singular space.

**Comment by wbprice** [comment]
Veni vidi ædificavit.
