### ISSUE TITLE
Make Beautiful Maps and Tell Stories with See Click Fix Issues

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/tasks#49]
See Click Fix is a platform for communicating with city services.

See Click Fix is used mainly to report and track public work issues, ex., potholes, graffiti, street lamps, but it's not limited to public works issues.

See Click Fix has a public API that works in any city. Here are some example of output:

Places in a City:
https://seeclickfix.com/api/v2/places?address=Virginia+Beach+VA
https://seeclickfix.com/api/v2/places?address=Norfolk+VA

Issues in a City or Place:
https://seeclickfix.com/api/v2/issues?place_url=virginia-beach&state=VA
https://seeclickfix.com/api/v2/issues?place_url=newport-news&state=VA

Data from these API end points can be processed and layered over maps to tell stories. When combined with layers from other kinds of data, ex., legislative district, those stories become even more interesting.

Make a responsive web page that tells one or more stories using maps, See Click Fix API, and other relevant data.
##

**Comment by troy0820** [comment]
Do you want to use leaflet for the map?

**Comment by cityofhamptonweb** [comment]
The City of Hampton is wanting to develop an online map of its neighborhoods and tell the story of each one once you click on the pinned/outlined neighborhood. The idea is to tell the history, provide information on services/events, and view videos so that visitors who are interested in moving to Hampton can get a better feel (virtually) of the neighborhood. It sounds as if this application would serve this purpose, could you tell me more? We were hoping to have something similar to this: 
http://www.colonialwilliamsburg.com/

**Comment by kmcurry** [comment]
@cityofhamptonweb That's awesome! Story Maps seems like a good tool for the job: http://storymaps.arcgis.com/en/ Another option is https://hrvawiki.org Someone at Colonial Williamsburg has done a great deal of content curation for that site. Do you already have the info for you locations or do you need to write and edit it?

**Comment by kmcurry** [comment]
@troy0820 I have no requirements for type of technology other than the result should be responsive web (HTML+CSS+JavaScript). Ask Jonah about which type of map tech.

**Comment by cityofhamptonweb** [comment]
@kmcurry Thanks so very much for the fast response! I will look into this and go from there; we do have the content but it's in the very beginning stages however I'm sure we'll be building on this as we go along. I very much appreciate your help on this.

**Comment by kmcurry** [comment]
@cityofhamptonweb You are welcome! That's what we do at [Code4HR](http://code4hr.org).

**Comment by qwo** [comment]
@cityofhamptonweb check out also http://storymap.knightlab.com/, its great

in action: http://hamptonroads.com/food/711606/2014/03/30-places-eat-virginia-you-die

**Comment by cityofhamptonweb** [comment]
Wow!! This is pretty cool too…and very easy to use…drumming up something quick now…THANKS!

Thanks!
[horizontal line]
Dacia D. Hollis | Website Manager | Marketing | O: 757-728-2032
[hampton_signature]http://hampton.gov/

**Comment by qwo** [comment]
no problem. can't wait to see what you folks are producing!
