### ISSUE TITLE
HRT Bus App: Posters

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#6]
- [x] Change pitch from marketing a survey about the app to marketing the app
- [ ] Print posters
- [ ] hang posters

**Comment by kmcurry** [comment]
Find your bus. Anytime. Anywhere.
http://hrtb.us

**Comment by kmcurry** [comment]
Use this :iphone: to find this :bus:
http://hrtb.us

**Comment by qwo** [comment]
Naming of the bus as "Where's My Bus" or "Where's my HRT BUS" was also discussed.

![czcqlnf](https://f.cloud.github.com/assets/3683993/679279/cb3c1e62-d95f-11e2-9fd1-47fe55d5b2fb.jpg)

**Comment by kmcurry** [comment]
Final version for tall poster:
https://docs.google.com/file/d/0B5fMNDGiGLqobExZN3BpNEYzdHM/edit?usp=sharing
Alternate:
https://docs.google.com/file/d/0B_WC8QOgiwjzYV9IWVVnYnFUWms/edit?usp=sharing

**Comment by kmcurry** [comment]
Pricing from Dominion Printers:

8mm card stock = $3.75 sq ft
10mm card stock = $5.00 sq ft
Vinyl = $5.00 sq ft

LRT Shelter Panel = 26.5" X 38.5"

Rough cost ~ 
8mm card stock ~ $28 each before tax
10mm card stock & vinyl ~ $36 each before tax

With a $200 budget we could get 5-7 prints. That's not a great ratio. Perhaps we can do better with a different vendor.

HRT Advertising Specs:
https://docs.google.com/file/d/0B_WC8QOgiwjzbXh5RmxhZi1KUFU/edit?usp=sharing

**Comment by kmcurry** [comment]
Bringing flyers to our meetup this week.
