### ISSUE TITLE
VBPD: Media strategy

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/tasks#7]
- [x] meeting minutes http://goo.gl/DMqKk
- [ ] Send CPU an agenda for a meeting with dept social media managers on setting facebook permissions, and hootsuite for social management.
- [ ] Intro to VBPD pagemaster and work on improving pages and resources for CPU offerings
- [ ] Ask Jason about short links, i.e. vbgov.com/cpu

**Comment by kmcurry** [comment]
- Engaging Crime Prevention Unit (CPU) volunteers in social media
- Managing group administration of social media accounts
- Publishing a CPU calendar of events

**Comment by kmcurry** [comment]
https://twitter.com/VBPD
https://twitter.com/VBPDTraffic

**Comment by BretFisher** [comment]
VBPD Seemed to have killed this effort. We'll re-open if they re-engage.
