### ISSUE TITLE
Daily Press Community Calendar 

### ISSUE THREAD

**Issue by qwo** [Code4HR/tasks#9]
Daily Press is piloting a calendar widget developed by our friends at Microsoft Research that presents _the most comprehensive_ aggregation of events in HRVA.

Daily Press needs assistance styling the widget.

The most pressing need is use of the widget on the homepage, where the left side is cut off.

(As of this writing it has been replaced by breaking news.)

The other need is the calendar page:
http://www.dailypress.com/entertainment/calendar/

We would like a web designer to re-imagine the look and feel of the widget and implement the necessary CSS.

Information about how to style stock widgets is in the [widget exploratorium](http://jonudell.net/elmcity/exploratorium.html?hub=HamptonRoadsVA&hubdesc=HamptonRoadsVA&tag=music&theme=a2chron)

Structured data for making your own widgets is available in all your favorite flavors under the Guide to URLs > Calendar Views on the [About page](http://elmcity.cloudapp.net/HamptonRoadsVA/about)

**Comment by kmcurry** [comment]
I think this is being covered through the collaboration we facilitated between Daily Press and Microsoft Research. The calendar site is evolving without our attention. There are some great filters, too. Try Poetry and Emergency Management. Something every night. There's always more that can be done with local calendars for sure.  Put new calendar ideas in the UserVoice. Some usability issues on the DP site but not sure where to report them. Not here in tasks.
